apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scaling
  name: selective-pods
  labels:
    app: nap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: picky
  template:
    metadata:
      labels:
        app: picky
    spec:
      nodeSelector:
        vmtype: special
      containers:
      - name: picky-containers
        image: https
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
