apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: large-pods
  namespace: scaling
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       large-pods
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: scalable-workload
  namespace: scaling
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       scalable-workload
  updatePolicy:
    updateMode: "Auto"
