apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
      type: nginx
  template:
    metadata:
      labels:
        app: web
        type: nginx
    spec: 
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m 
            memory: 100Mi
        readinessProbe:
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      type: nginx
  template:
    metadata:
      labels:
        app: web
        type: nginx
    spec: 
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m 
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
      type: apache
  template:
    metadata:
      labels:
        app: web
        type: apache
    spec: 
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m 
            memory: 100Mi
