apiVersion: v1
kind: Service
metadata:
  name: stateful
  labels:
    app: stateful
spec:
  ports:
  - port: 80
  selector:
    app: stateful
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
spec:
  replicas: 3
  serviceName: stateful
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful      
    spec:
      containers:
      - name: stateful
        image: nginx:latest
        ports:
        - containerPort: 80
