apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      test: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        test: db
    spec:
      containers:
      - name: sqldb
        env:
        - name: MYSQL_USER
          value: pattypatpat
        - name: MYSQL_PASSWORD
          value: patpatpat
        image: mariadb:latest
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            # Check if we can execute basic query.
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 10
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
